import "./globals.css";

import Nav from "./Components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`w-screen h-screen overflow-hidden bg-[#EEDDCC]`}
      >
        <main className="w-full h-full container mx-auto   bg-[#EEDDCC] overflow-scroll no_scrollbar ">
          <Nav />
          {children}
        </main>

      </body>

    </html>
  );
}
